### ISSUE TITLE
NiceToHave: Hand-entered folder identifiers

### ISSUE THREAD

**Issue by wtanksleyjr** [terminalnetwork/syncthing-hooks#1]
Obviously this isn't a bug, but it would be nice to support folder identifiers that were hand-entered. Most of mine were done that way, as there's no obvious reason not to and some reasons to prefer that.

Just something for the wishlist.

**Comment by aengl** [comment]
Thanks for the feedback! That will be easy to support, I'll try to get around to releasing a new version this week ☺️
